{
    "name": "payment_monero_rpc",
    "summary": "Allows you to accept Monero Payments on the Online Market and POS",
    "author": "Monero Integrations",
    "website": "https://monerointegrations.com/",
    "category": "Accounting/Payment Providers",
    "version": "18.0.0.0.2",
    "depends": [
    	"account",
        "website_sale",
        "website_payment",
        "website",
        "payment",
        "queue_job",
        "base_setup",
        "web",
        "point_of_sale",
        "pos_online_payment",
    ],
    "external_dependencies": {
    	"python": ["monero"],
    	"npm": ["monero-ts", "crypto-browserify", "stream-browserify", "buffer"]
    },
    "data": [
    	"security/ir.model.access.csv",
    	"data/mail_templates.xml",
		"data/monero_payment_data.xml",
		"views/monero_daemon_views.xml",
		"views/monero_payment_views.xml",
    	    "views/monero_payment_templates.xml",
        "views/monero_payment_template_confirmation.xml",
        "views/monero_payment_template_email.xml",
        "views/monero_payment_template_invoice.xml",
        "views/monero_payment_template_proof.xml",
		"views/monero_payment_kanban.xml",
		"views/pos_payment_views.xml",
		"views/menus.xml",
		"data/monero_cron.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "payment_monero_rpc/static/src/css/monero.css",
            "payment_monero_rpc/static/src/css/monero_pos.css",
            "payment_monero_rpc/static/src/css/payment_page.css",                        
            "payment_monero_rpc/static/src/js/payment_form_monero.js",
            "payment_monero_rpc/static/src/js/payment_monero_checkout.js",
        ],
        "web.assets_qweb": [
            "payment_monero_rpc/static/src/xml/monero_payment_template_page.xml",
        ],
        "point_of_sale._assets_pos": [
            "payment_monero_rpc/static/src/app/online_payment_popup_monero.js",
            "payment_monero_rpc/static/src/app/payment_screen_monero.js",
            "payment_monero_rpc/static/src/app/online_payment_popup_monero.xml",
        ],                    
    },
    "demo": [
        "demo/demo.xml",
    ],
    "installable": True,
    "application": True,
    "classifiers": ["License :: OSI Approved :: MIT License"],
    'post_init_hook': 'associate_monero_with_pos_configs',
}
