dist: Focal
language: python
cache:
  directories:
    - $HOME/.cache/pip
    # Add cache for pre-commit on repo that uses it (mandatory for >= 13)
    - $HOME/.cache/pre-commit

python:
  # For branches <= 10.0, put `- "2.7.13"`
  # For branches 11.0 and 12.0, put `- "3.5"`
  - "3.7"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - python-lxml  # because pip installation is slow
#     For wkhtmltopdf, see the env section below

before_script:
  - sudo systemctl start postgresql
  - psql -c "CREATE USER travis WITH PASSWORD 'travis';" -U postgres
  - psql -c "ALTER USER travis CREATEDB;" -U postgres

stages:
  - linting
  - test

jobs:
  include:
    # use this linting job repos that use pre-commit (mandatory for >= 13)
    - stage: linting
      name: "pre-commit"
      python: "3.7"  # Black requires python >= 3.6
      install: pip install pre-commit
      script: pre-commit run --all --show-diff-on-failure --verbose --color always
      after_success:
      before_install:
    # use this linting job for repos that do not use pre-commit (default for < 13)
    - stage: linting
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        # add MAKEPOT="1" to a TEST line to export .pot files from
        # the test database after test success
        - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB"
    # Other env possibilities:
    # use this to install a standalone database to export .pot files
    # - MAKEPOT="1"
    # either use the two lines above or the two below. Don't change the default if
    # it's not necessary (it is only necessary if modules in your repository can't
    # be installed in the same database. And you get a huge speed penalty in your
    # tests)
    #  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
    #  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

env:
  global:
    - VERSION="14.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    # Set this variable to some version existing as linux-generic build on
    # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
    # if you need to install wkhtmltopdf
    # - WKHTMLTOPDF_VERSION="0.12.5"
    # Set the above to install a `wkhtmltopdf` version that is not the one provided
    # by the `pov-wkhtmltopdf` repo.
    - MQT_DEP=PIP
    - PHANTOMJS_VERSION="latest"
    # The above line controls the PhantomJS version that is used for JS testing.
    #   It is not necessary to include this value unless you are altering the default.
    #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
    - WEBSITE_REPO="1"
    # Use the above line to install dependencies that are required for website repos:
    # * SASS & Bootstrap-SASS
    # * Compass

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
